server:
  port: 1111

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    
  instance:
    hostname: vm-registration
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 7
    
  server:
    enableSelfPreservation: false
  
  serviceUrl:
    defaultZone: http://localhost:1111/eureka/
    
spring:
  application:
    name: ozthra-registration-server