server:
  port: 1111

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    
  serviceUrl:
    defaultZone: http://localhost:1111/eureka/
    
spring:
  application:
    name: ozthra-registration-server